# Generated by Django 3.2.20 on 2023-09-05 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemname', models.CharField(max_length=30)),
                ('itemcode', models.CharField(max_length=10)),
                ('salestax', models.CharField(max_length=5)),
                ('mrp', models.IntegerField()),
                ('barcode', models.CharField(max_length=10)),
                ('hsncode', models.CharField(max_length=10)),
                ('purchasetax', models.CharField(max_length=5)),
            ],
        ),
    ]
