# Generated by Django 3.2.20 on 2023-09-07 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hiapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryname', models.CharField(max_length=30)),
                ('categorydescription', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='itemmaster',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='hiapp.categorymaster'),
        ),
    ]
