# Generated by Django 3.2.20 on 2023-09-07 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hiapp', '0002_auto_20230907_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemmaster',
            name='category',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='hiapp.categorymaster'),
        ),
    ]
