# Generated by Django 3.2.20 on 2023-09-14 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hiapp', '0004_auto_20230910_1945'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartyMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partyname', models.CharField(max_length=30)),
                ('partycode', models.CharField(max_length=10)),
                ('address1', models.TextField()),
                ('address2', models.TextField()),
                ('city', models.CharField(max_length=25)),
                ('state', models.CharField(max_length=20)),
                ('pin', models.CharField(max_length=10)),
                ('mobile1', models.CharField(max_length=12)),
                ('mobile2', models.CharField(max_length=12)),
                ('email', models.CharField(max_length=40)),
                ('gst', models.CharField(max_length=5)),
                ('pricelist', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchaseno', models.CharField(max_length=20)),
                ('purchasedate', models.DateField(auto_now_add=True)),
                ('supinvoiceno', models.CharField(max_length=20)),
                ('suplierDate', models.DateField(auto_now_add=True)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('credit', 'Credit')], default='credit', max_length=10)),
                ('unit', models.CharField(max_length=15)),
                ('mrp', models.IntegerField(blank=True, null=True)),
                ('purchasetax', models.CharField(blank=True, max_length=5)),
                ('grandtotal', models.IntegerField()),
                ('purchaseitem', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='hiapp.itemmaster')),
                ('supplier', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='hiapp.partymaster')),
            ],
        ),
    ]
