# Generated by Django 3.2.20 on 2023-09-14 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hiapp', '0005_partymaster_purchasemodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasemodel',
            name='purchaseitem',
        ),
        migrations.RemoveField(
            model_name='purchasemodel',
            name='supplier',
        ),
        migrations.DeleteModel(
            name='PartyMaster',
        ),
        migrations.DeleteModel(
            name='PurchaseModel',
        ),
    ]
