# Generated by Django 3.2.20 on 2023-09-15 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiapp', '0006_auto_20230914_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemmaster',
            name='purchasetax',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='itemmaster',
            name='salestax',
            field=models.IntegerField(),
        ),
    ]
