# Generated by Django 3.2.20 on 2023-09-28 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiapp', '0007_auto_20230915_1019'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricelistMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pricelistname', models.CharField(max_length=30)),
                ('pricelistdescription', models.TextField()),
            ],
        ),
    ]
