# Generated by Django 3.2.20 on 2023-09-28 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hiapp', '0008_pricelistmaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemPricelistMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pricename', models.CharField(max_length=30)),
                ('mrp', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('itemid', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='hiapp.itemmaster')),
                ('pricelist', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='hiapp.pricelistmaster')),
            ],
        ),
    ]
