# Generated by Django 3.2.20 on 2023-10-04 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiapp', '0009_itempricelistmaster'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempricelistmaster',
            name='itemid1',
            field=models.IntegerField(default=23),
            preserve_default=False,
        ),
    ]
