# Generated by Django 3.2.20 on 2023-09-09 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PartyMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partyname', models.CharField(max_length=30)),
                ('partycode', models.CharField(max_length=10)),
                ('address1', models.TextField()),
                ('address2', models.TextField()),
                ('city', models.CharField(max_length=25)),
                ('state', models.CharField(max_length=20)),
                ('pin', models.CharField(max_length=10)),
                ('mobile1', models.CharField(max_length=12)),
                ('mobile2', models.CharField(max_length=12)),
                ('email', models.CharField(max_length=25)),
                ('gst', models.CharField(max_length=5)),
                ('pricelist', models.CharField(max_length=15)),
            ],
        ),
    ]
