# Generated by Django 3.2.20 on 2023-09-10 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partyapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partymaster',
            name='email',
            field=models.CharField(max_length=40),
        ),
    ]
