# Generated by Django 3.2.20 on 2023-09-21 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partyapp', '0002_alter_partymaster_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_number', models.CharField(max_length=10)),
                ('date', models.DateField(auto_now=True)),
                ('partyname', models.CharField(max_length=40)),
                ('party', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='partyapp.partymaster')),
            ],
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemname', models.CharField(max_length=100)),
                ('mrp', models.IntegerField()),
                ('unit', models.CharField(max_length=15)),
                ('purchasetax', models.IntegerField()),
                ('totalqty', models.IntegerField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sale_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partyapp.salemodel')),
            ],
        ),
    ]
