# Generated by Django 3.2.20 on 2023-09-21 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partyapp', '0003_saleitem_salemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleitem',
            name='mrp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
