# Generated by Django 3.2.20 on 2023-09-22 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partyapp', '0005_auto_20230922_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleitem',
            name='itemname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
