# Generated by Django 3.2.20 on 2023-09-25 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partyapp', '0006_alter_saleitem_itemname'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prchase_number', models.CharField(max_length=15)),
                ('date', models.DateField(auto_now=True)),
                ('supinvoiceno', models.CharField(max_length=15)),
                ('supdate', models.DateField(auto_now=True)),
                ('partyname', models.CharField(max_length=40)),
                ('grandtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash Purchase'), ('credit', 'Credit')], max_length=10)),
                ('party', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='partyapp.partymaster')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemname', models.CharField(blank=True, max_length=100, null=True)),
                ('mrp', models.IntegerField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, max_length=15, null=True)),
                ('purchasetax', models.IntegerField(blank=True, null=True)),
                ('totalqty', models.IntegerField(blank=True, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('purchase_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partyapp.purchasemodel')),
            ],
        ),
    ]
