# Generated by Django 3.2.20 on 2023-09-25 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partyapp', '0007_purchaseitem_purchasemodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchasemodel',
            old_name='prchase_number',
            new_name='purchase_number',
        ),
    ]
