# Generated by Django 3.2.20 on 2023-09-25 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partyapp', '0008_rename_prchase_number_purchasemodel_purchase_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upiamt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('swipe', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cash', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cashtendred', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('osamt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('creditamt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partyapp.purchasemodel')),
            ],
        ),
    ]
