# Generated by Django 3.2.20 on 2023-09-26 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partyapp', '0010_salemodel_grandtotal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salepayment',
            name='payment_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partyapp.salemodel'),
        ),
    ]
