# Generated by Django 3.2.20 on 2023-09-27 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partyapp', '0011_alter_salepayment_payment_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salemodel',
            name='sale_number',
            field=models.CharField(max_length=20),
        ),
    ]
